print("========== OPERATOR IDENTITAS ==========\n")
nilai1 = 8
nilai2 = 9 
nilai3 = 2 
print("=========== IS =========\n")

# IS
print("nilaia is nilai2 :", nilai1 is nilai2)
print("nilai2 is nilai1 :", nilai2 is nilai1) 
print("nilai3 is nilai2:" , nilai3 is nilai1) 
print("nilai2 is nilai3 :" , nilai2 is nilai3) 
print("=========IS NOT===========\n")

# is not 
print("nilai1 is not nilai2 :",nilai1 is not nilai2) 
print("nilai2 is not nilai1 :",nilai2 is not nilai1) 
print("nilai3 is not nilai1 :",nilai3 is not nilai1) 
print("nilai2 is not nilai3 :",nilai2 is not nilai3)   

print("====================\n")
nama1 = "fisah" 
nama2 = "arif"
print("nama1 is nama2 :", nama1 is nama2)
print("nama1 is not nama2 :", nama1 is not nama2)