# menggunakan inputan user
print("_________BIOATAKU_________")
nama = input("Masukkan nama anda :")
nim = input("Masukkan nim anda : ")
tgl_lahir = int(input("masukkan tanggal lahir : "))
bulan_lahir = int(input("Masukkan bulan lahir anda : "))
tahun_lahir = int(input("Masukkan tahun lahir anda : "))
umur = int(input("Masukkan umur anda : "))
tinggi = float(input("Masukkan tinngi badan anda : "))
status = bool(input("Masukkan status anda : "))
print("_____________________________")

print("Nama           : ", nama)
print("Nim            : ", nim)
print("tanngal lahir  : ", tgl_lahir)
print("Bulan lahir    : ", bulan_lahir)
print("Tahun Lahir    : ", tahun_lahir)
print("Umur           : ", umur, "tahun")
print("tinngi badan   : ", tinggi, "cm")
print("Staus, Mahasiswa : ", status)

